## Adaptive Signal Processing

#### Estimation, system identification, and Wiener solution

###### Author: Xunzhe Wen  <br>

In [1]:
import scipy
import numpy as np
import matplotlib.pyplot as plt
from scipy import fftpack
from scipy import signal
from scipy import random
from scipy import linalg

plt.close('all')
random.seed(1234)

# Paramters Initialization
L = 10000
std_v = 1
std_s = np.sqrt(10)
mu = 0   ### zero mean

# Signal Generation
s = np.random.normal(mu,std_s,L)
v = np.random.normal(mu,std_v,L)

# FIR Filters
g = [1,1]
h = [1,2,1]
lag_ss = [10]


# FIR System
x = signal.convolve(s,g)
t = signal.convolve(x,h)
d = t[0:L]+v
lag_xx = signal.convolve(signal.convolve(lag_ss,g),g[::-1]) 
lag_dd = signal.convolve(signal.convolve(lag_xx,h),h[::-1])
lag_dx = signal.convolve(lag_xx,h)
power_d=lag_dd[3]+1

Question 1 was solved manually.

Question 2:

In [20]:
# Question 2:

R1 = np.array([[lag_xx[1],lag_xx[2],0],[lag_xx[2],lag_xx[1],lag_xx[2]],[0,lag_xx[2],lag_xx[1]]])
p1 = (np.array([lag_dx[1],lag_dx[2],lag_dx[3]]))

MMSE=power_d-p.T.dot(linalg.inv(R)).dot(p)

print(MMSE)

1.0


Question 3:

In [21]:
w=linalg.inv(R).dot(p)

print(w)

[ 1.  2.  1.]


Question 4:

In [22]:
MSE=power_d-w.T.dot(p)-w.T.dot(p)+w.T.dot(R).dot(w) # Real Valued

print(MSE)

1.0


Question 5:

In [23]:
y=signal.convolve(x,w)
e=d-y[:L]

MSE=np.sum(e**2)/len(e)

print (MSE)

0.988229641629


Question 6: 

In [24]:
# Unbiased Estimation Auto-correlation of x
estimated_xx = np.correlate(x[0:L],x[0:L],"full")
term = np.arange(L,0,-1)
unbiased_estimated_xx = estimated_xx[L-1:]/term

# Unbiased Estimation Cross-correlation of d and x
estimated_dx = np.correlate(d[0:L],x[0:L],"full")
unbiased_estimated_dx = estimated_dx[L-1:]/term

Question 7:

In [25]:
xx = unbiased_estimated_xx[:3]
dx = unbiased_estimated_dx[:3]

R2 = np.array([[xx[0],xx[1],xx[2]],[xx[1],xx[0],xx[1]],[xx[2],xx[1],xx[0]]])
p2 = np.array([dx[0],dx[1],dx[2]])

W2=linalg.inv(R2).dot(p2.T)

print(W2)

[ 0.99728577  2.00465879  0.99863764]


Question 8:

In [26]:
MSE2=power_d-W2.T.dot(p2)-W2.T.dot(p2)+W2.T.dot(R2).dot(W2) # Real Valued

print(MSE2)

1.21062794218


Question 9:

In [32]:
x=x[0:L]
d=d[0:L]

# Fourior Transform
nperseg=256
overlap=nperseg/2
nfft=nperseg

freqtmp, Pxx = signal.csd(x, x, fs=1.0, window='hann', nperseg=nperseg, noverlap=overlap, nfft=nfft,
                         detrend=False, return_onesided=False, scaling='density', axis=-1)
freqtmp, Pdx = signal.csd(d, x, fs=1.0, window='hann', nperseg=nperseg, noverlap=overlap, nfft=nfft,
                         detrend=False, return_onesided=False, scaling='density', axis=-1)

w3=Pdx/Pxx

# Inverse Fourior Transform
w3=fftpack.ifftshift(np.real(fftpack.ifft(w3)))[126:129] # Coeff allocated in the middle
w3=np.vstack((np.reshape(w3,(1,-1)).T,0))[:3]
w3=w3[:3]

print(w3)

[[ 1.00427227]
 [ 1.99902679]
 [ 1.0028289 ]]


Question 10:

In [31]:
MSE=power_d-w3.T.dot(p1)-w3.T.dot(p1)+w3.T.dot(R1).dot(w3) # Real Valued

print(MSE)

[[ 1.00040582]]
